# Generated by Django 3.2.6 on 2022-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='brand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='title',
            field=models.TextField(),
        ),
    ]
